// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSxYhWtylGVeRgvWITxLKVRJW79xLyi_s',
    appId: '1:854344486458:web:3fc351eefebd9abd4d6f03',
    messagingSenderId: '854344486458',
    projectId: 'testing-cli-28f87',
    authDomain: 'testing-cli-28f87.firebaseapp.com',
    storageBucket: 'testing-cli-28f87.firebasestorage.app',
    measurementId: 'G-QJ97XRS20Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdzZCAvKIIsVOurLOyWkBvc3bEmdq-ehA',
    appId: '1:854344486458:android:b4d7a112a021d6794d6f03',
    messagingSenderId: '854344486458',
    projectId: 'testing-cli-28f87',
    storageBucket: 'testing-cli-28f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6bmVAvanthZGbERRPdizXaITu86iFzA',
    appId: '1:854344486458:ios:403cf6ece2eab2a34d6f03',
    messagingSenderId: '854344486458',
    projectId: 'testing-cli-28f87',
    storageBucket: 'testing-cli-28f87.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6bmVAvanthZGbERRPdizXaITu86iFzA',
    appId: '1:854344486458:ios:403cf6ece2eab2a34d6f03',
    messagingSenderId: '854344486458',
    projectId: 'testing-cli-28f87',
    storageBucket: 'testing-cli-28f87.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSxYhWtylGVeRgvWITxLKVRJW79xLyi_s',
    appId: '1:854344486458:web:ac475a12151095a24d6f03',
    messagingSenderId: '854344486458',
    projectId: 'testing-cli-28f87',
    authDomain: 'testing-cli-28f87.firebaseapp.com',
    storageBucket: 'testing-cli-28f87.firebasestorage.app',
    measurementId: 'G-J9Z80HXWM9',
  );
}
